import type { WeaponDef } from './types';

// ===== ترسانة الصياد — تُفتح تباعاً عند الفوز بالمراحل =====
export const WEAPONS: WeaponDef[] = [
  {
    id: 'netgun',
    name: 'بندقية الشباك',
    desc: 'سلاح الصياد الكلاسيكي — طلقة شبكية دقيقة وموثوقة.',
    damage: 1,
    fireRate: 4.2,
    bulletSpeed: 950,
    pellets: 1,
    spread: 0,
    pierce: 0,
    homing: false,
    bulletColor: '#a7f3d0',
    bulletSize: 7,
    unlockLevel: 1,
    kick: 60,
  },
  {
    id: 'scatter',
    name: 'المشتّت المزدوج',
    desc: 'ماسورتان نحاسيتان تطلقان رشقة مزدوجة واسعة.',
    damage: 1,
    fireRate: 3.4,
    bulletSpeed: 900,
    pellets: 2,
    spread: 0.14,
    pierce: 0,
    homing: false,
    bulletColor: '#fcd34d',
    bulletSize: 7,
    unlockLevel: 3,
    kick: 120,
  },
  {
    id: 'plasma',
    name: 'البلازما الثلاثية',
    desc: 'مدفع تروس يطلق ثلاث شحنات بلازما زرقاء مدمّرة.',
    damage: 1,
    fireRate: 5,
    bulletSpeed: 1050,
    pellets: 3,
    spread: 0.16,
    pierce: 1,
    homing: false,
    bulletColor: '#67e8f9',
    bulletSize: 8,
    unlockLevel: 6,
    kick: 90,
  },
  {
    id: 'viper',
    name: 'أنياب الأفعى',
    desc: 'رصاصات خارقة ثقيلة تخترق صفوف الفراشات.',
    damage: 2,
    fireRate: 5.5,
    bulletSpeed: 1250,
    pellets: 1,
    spread: 0,
    pierce: 3,
    homing: false,
    bulletColor: '#4ade80',
    bulletSize: 8,
    unlockLevel: 10,
    kick: 140,
  },
  {
    id: 'storm',
    name: 'عاصفة الرصاص',
    desc: 'مدفع رشاش دوّار يمطر الأعداء بوابل لا يتوقف.',
    damage: 1,
    fireRate: 11,
    bulletSpeed: 1150,
    pellets: 1,
    spread: 0.05,
    pierce: 0,
    homing: false,
    bulletColor: '#fdba74',
    bulletSize: 6,
    unlockLevel: 16,
    kick: 40,
  },
  {
    id: 'seeker',
    name: 'الصواريخ الصائدة',
    desc: 'قذائف ذكية تتعقّب الفراشات أينما فرّت.',
    damage: 3,
    fireRate: 3.2,
    bulletSpeed: 720,
    pellets: 1,
    spread: 0,
    pierce: 0,
    homing: true,
    bulletColor: '#f0abfc',
    bulletSize: 10,
    unlockLevel: 25,
    kick: 200,
  },
  {
    id: 'cosmos',
    name: 'المدفع الكوني',
    desc: 'سلاح أسطوري من قلب النجوم — رشقات كونية خارقة.',
    damage: 4,
    fireRate: 7,
    bulletSpeed: 1450,
    pellets: 3,
    spread: 0.12,
    pierce: 5,
    homing: false,
    bulletColor: '#c4b5fd',
    bulletSize: 10,
    unlockLevel: 40,
    kick: 160,
  },
];

export const weaponById = (id: string): WeaponDef =>
  WEAPONS.find((w) => w.id === id) ?? WEAPONS[0];

export const unlockedWeapons = (maxLevelBeaten: number): WeaponDef[] =>
  WEAPONS.filter((w) => w.unlockLevel <= Math.max(1, maxLevelBeaten + 1));

export const weaponForLevelReward = (beatenLevel: number): WeaponDef | undefined => {
  // عند الفوز بمرحلة تساوي شرط فتح سلاح → يكسبه الصياد
  return WEAPONS.find((w) => w.unlockLevel === beatenLevel + 1);
};
